### ISSUE TITLE
Allow community members to run the website locally

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/hub.getdbt.com#1788]
## Overview
As noted in #1774, there's a private submodule that is a blocker for building locally for any community members outside of the dbt-labs organization.

If we remove this blocker, than any community member can build the [hub.getdbt.com](https://github.com/dbt-labs/hub.getdbt.com) website locally and participate in development.

## Implementation steps
- [X] copy the CSS files from the `fishtown-analytics/www.getdbt.com` submodule to an internal folder.
    - #1782
- [X] remove it from `.gitmodules`
    - #1782
- [x] remove it from any instructions (like [here](https://github.com/dbt-labs/hub.getdbt.com/blob/24f0eb7aff841fdbf6418f68f9f7f4e13135047f/CONTRIBUTING.md#development))
    - #1789
- [X] add a Dockerfile
    - #1794
- [ ] add a docker-compose and instructions
    - #1802
